#!/bin/bash
# This bash script defines path variables to configure the EMAS interface

# The absolute directory of the EMAS repository
export BASE_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# The absolute directory of the Simulator 
export SIMULATOR_DIRECTORY="${BASE_DIRECTORY}/Simulator"

# The absolute directory of the Simulator config files 
export SIMULATOR_CONFIG_DIRECTORY="${SIMULATOR_DIRECTORY}/Config"

# The absolute directory of the Gem5
export GEM5_DIRECTORY="${SIMULATOR_DIRECTORY}/GEM5/gem5"

# The absolute directory of the Simulator output 
export WORK_DIRECTORY="${BASE_DIRECTORY}/Work"

# The absolute directory of shell utilities 
export INTERFACE_DIRECTORY="${BASE_DIRECTORY}/Interface"

# The absolute directory of scenario scripts 
export SCENARIO_DIRECTORY="${BASE_DIRECTORY}/Scenarios"

# ===================================================
# =============== LOAD STATE VARIABLES ==============
# ===================================================
export STATE_FILE="${BASE_DIRECTORY}/state"
export STATE_FILE_LOCK="${STATE_FILE}.lock"
export STATE_FILE_DEFAULT="${STATE_FILE}.default"