#!/bin/bash
# This bash script defines path variables to configure the EMAS interface

# The absolute directory of the EMAS repository
export BASE_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# The absolute directory of shell utilities 
export INTERFACE_DIRECTORY="${BASE_DIRECTORY}/Interface"

# The absolute directory of scenario scripts 
export SCENARIO_DIRECTORY="${BASE_DIRECTORY}/Scenarios"

# ===================================================
# ================ Simulator Files ==================
# ===================================================

# The absolute directory of the Simulator 
export SIMULATOR_DIRECTORY="${BASE_DIRECTORY}/Simulator"

# The absolute directory of the Simulator config files 
export SIMULATOR_CONFIG_DIRECTORY="${SIMULATOR_DIRECTORY}/Config"

# The absolute directory of the Gem5
export GEM5_SRC_DIRECTORY="${SIMULATOR_DIRECTORY}/GEM5/gem5"

# The absolute location of Gem5 disk utility
export GEM5_DISK_UTIL="${GEM5_SRC_DIRECTORY}/util/gem5img.py"

# ===================================================
# =================== Work Files ====================
# ===================================================

# The absolute directory of the Simulator output 
export WORK_DIRECTORY="${BASE_DIRECTORY}/Work"

# The absolute directory of the Simulator output 
export DISK_IMG_DIRECTORY="${WORK_DIRECTORY}/disk-images"

# The absolute directory of the Simulator output 
export SCENARIO_OUTPUT_DIRECTORY="${WORK_DIRECTORY}/Scenarios"

# The absolute directory of the Simulator output 
export GEM5_BUILD_DIRECTORY="${WORK_DIRECTORY}/build"

# The absolute directory of the Temporary mounting directory
export GEM5_TEMP_MNT_DIRECTORY="${WORK_DIRECTORY}/mnt"

# ===================================================
# =================== State Files ===================
# ===================================================
export STATE_FILE="${BASE_DIRECTORY}/state"
export STATE_FILE_LOCK="${STATE_FILE}.lock"
export STATE_FILE_DEFAULT="${STATE_FILE}.default"